export const AgencySelectors={
    addAgencyAccountBtn:'button[class="relative btn-typo-16 Button_button__XQZs8 Button_primary__Y_gT8"]',
    accountName:'input[placeholder="Enter account name"]',
    accountAddress:'//span[text()="Address Line 1"]//parent::div//div//input[@class="Input_input__rnmyh Input_lg__lcP1K"]',
    accountCity:'//span[text()="City"]//parent::div//div[@class="Input_inputContainer__AqMye"]',
    stateDropDown:'//span[text()="State"]//parent::div//div[@class="Input_inputContainer__AqMye"]',
    selectState:'//div[@id="react-select-3-listbox"]//div//div[text()="Arkansas (AR)"]',
    accountPostalCode:'//span[text()="Postal Code"]//parent::div//div[@class="Input_inputContainer__AqMye"]',
    accountPhoneNumber:'input[class="form-control "]',
    timeZoneDropDown:'#react-select-4-input',
    selectTimeZone:'#react-select-4-option-0',
    accountUrlSlug:'//span[text()="https://"]//parent::div//div[@class="Input_mainContainer__z6cH9"]',
    accountLogoField:'input[accept="image/*"]',
    imageUploadModal:'div[id="modal"]',
    imageUploadSaveBtn:'//button//div[text()="Save"]',
    createAccountBtn:'//div[contains(text(), "Create Account")]//parent::button',
    agencySuccessMessage:'//div[text()="Agency Created Successfully!"]',
    addClientBtn:'//button//div[text()="Add Client"]',
    clientName:'input[placeholder="Enter client name"]',
    clientLogoField:'input[accept="image/*"]',
    saveAndContinueBtn:'//button//div[text()="Save & Continue"]',
    searchField:'input[placeholder="Search"]',
    organizationProfilePageHeading:'//div[text()="Organization Profile"]',
    selectOrgState:'#react-select-5-option-1',
    orgWebsite:'input[placeholder="https://www.example.com"]',
    orgTagline:'input[placeholder="Organization Tagline"]',
    orgBussinessOverview:'textarea[placeholder="Organization Summary"]',
    financialProfilePageHeading:'//div[text()="Financial Profile"]',
    entityTypeDropDown:'//span[text()="Entity Type"]//parent::div//div[@class="Input_inputContainer__AqMye"]',
    selectEntitytype:'#react-select-6-option-0',
    taxBasisDropDown:'//span[text()=" Tax Basis"]//parent::div//div[@class="Input_inputContainer__AqMye"]',
    selectTaxBasis:'#react-select-7-option-0',
    stateOfIncorporationDropDown:'//span[text()="State Of Incorporation"]//parent::div//div[@class="Input_inputContainer__AqMye"]',
    selectStateOfIncorporation:'#react-select-8-option-0',
    hubAnalyticUser:'//span[text()="HUB Analytics Users"]',
    addHubAnalyticUserBtn:'//button//div[text()="Add HUB Analytics User"]',
    hubAnalyticUserFirstName:'input[placeholder="Enter First Name"]',
    hubAnalyticUserLastName:'input[placeholder="Enter Last Name"]',
    hubAnalyticEmail:'input[placeholder="Enter Email"]',
    hubAnalyticPhoneNumber:'input[class="form-control "]',
    permissionRadioBtn:'//div[@class="w-max flex items-center gap-2"]/*[@stroke="currentColor"]',
    selectAccess:'//div[@class="w-full flex flex-col gap-4"]//div//div/*[@stroke="currentColor"]',
    reviewDetailsBtn:'//button//div[text()="Review Details"]',
    verifyUserDetails:'//span[text()="User Details"]',
    createUserBtn:'//button//div[text()="Create User"]',
    publishingRequirments:'//span[text()="Publishing Requirements"]',
    publishingRequirmentPageHeading:'//div[text()="Publishing Requirements Settings"]',
    publishingRequirmentEditBtn:'//button//div[text()="Edit"]',
    publishingRequirmentsCheckBoxes:'//div[@class="flex flex-col w-full"]//div//div//div//div/*[@stroke="currentColor"]',
    saveBtn:'//button//div[text()="Save"]',
    publishingRequirmentUpdatedSuccessMessage:'//div[text()="Publishing Requirements Updated!"]',
    agencyFilterDropDown:'//div[text()="All"]',
    selectActiveFilter:'#react-select-2-option-1',
    selectDeactivetedFilter:'#react-select-2-option-2',
    deactivateModal:'//span[text()="Deactivate Account"]',
    activateModal:'//span[text()="Activate Account"]',
    yesBtn:'//button//div[text()="Yes"]',
    deactivateAgencySuccessMessage:'//div[text()="Deactivated Successfully."]',
    activateAgencySuccessMessage:'//div[text()="Activated Successfully."]',


}