export const ClientSelectors = {
    clientName:'//div[text()="TGG client5878"]',
    addAdvisorBtn:'//div[text()="Company Advisors"]//parent::div//div//parent::div//parent::div//parent::div[@class="cursor-pointer absolute right-4 top-4"]',
    addAdvisorModal:'//div[text()="Add Advisors"]',
    instituationName:'input[placeholder="Enter Institution Name"]',
    contactFirstName:'input[placeholder="Enter First Name"]',
    contactLastName:'input[placeholder="Enter Last Name"]',
    contactEmail:'input[placeholder="Enter Email"]',
    advisorTypeDropDown:'//span[text()="Advisor Type"]//parent::div//div[@class="Input_inputContainer__AqMye"]',
    selectAdvisorType:'//div[text()="Bank"]',
    savaAndCloseBtn:'//button//div[text()="Save & Close"]',
    addExecutiveMemberBtn:'//div[text()="Management & Ownership"]//parent::div//div//parent::div//parent::div//parent::div[@class="cursor-pointer absolute right-4 top-4"]',
    selectAddExectiveMember:'//ul[@class="szh-menu szh-menu--state-open szh-menu--dir-bottom"]/*[text()="Add Executive Member"]',
    addClientExectiveModal:'//div[@class="flex flex-col pb-4 mr-6"]//div[text()="Add Client Executive"]',
    executiveFirstName:'input[placeholder="Enter First Name"]',
    executiveLastName:'input[placeholder="Enter Last Name"]',
    executiveEmail:'input[placeholder="Enter Email"]',
    executiveRoleDropDown:'//span[text()="Executive Role"]//parent::div//div[@class="Input_inputContainer__AqMye"]',
    selectExecutiveRole:'//div[text()="CEO"]',
    inviteUserToPlatformCheckBox:'//div[@class="w-max flex items-center gap-2"]/*[@stroke="currentColor"]',
    addExecutiveBtn:'//button//div[text()="Add Executive"]',
    addClientUsersBtn:'//div[text()="Client Users"]//parent::div//div//parent::div//parent::div//parent::div[@class="cursor-pointer absolute right-4 top-4"]',
    addClientUserModal:'.SideDrawer_childContainer__8b_jJ.overflow-auto.hide-scrollbar',
    addClientUserFirstName:'input[placeholder="Enter First Name"]',
    addClientUserLastName:'input[placeholder="Enter Last Name"]',
    addClientUserEmail:'input[placeholder="Enter Email"]',
    inviteClientUserBtn:'//button//div[text()="Invite Client User"]',
    addAccountingTeamBtn:'//div[text()="Agency Accounting Team"]//parent::div//div//parent::div//parent::div//parent::div[@class="cursor-pointer absolute right-4 top-4"]',
    addAccountingTeamModal:'//div[@class="flex flex-col pb-4 mr-6"]//div[text()="Add Accounting Team"]',
    accountingTeamRoleDropDown:'//span[text()="Role"]//parent::div//div[@class="Input_inputContainer__AqMye"]',
    selectAccountingRole:'//div[text()="CFO"]',
    selectHubAnalyticsUsers:'//div[@class="flex flex-col gap-4 moveToDown"]//div//div/*[@stroke="currentColor"]',
    saveAndCloseBtn:'//button//div[text()="Save & Close"]',
    companyGoalsMenu:'//span[text()="Company Goals"]',
    longTermGoalCreateBtn:'//div[text()="Create"]',
    longTermCompanyGoalModal:'//div[text()="Create Long Term Company Goal"]',
    longTermCompanyGoalTextField:'textarea[placeholder="Enter Long Term Company Goal"]',
    longTermGoalSaveBtn:'//div[text()="Save"]',
    addGoalBtn:'//button//div[text()="Add a Goal"]',
    editLongTermGoalBtn:'.neu-pencil',
    editLongTermCompanyGoalModal:'//div[text()="Edit Long Term Company Goal"]',
    deleteGoalBtn:'//div[@class="border-2 p-1 border-accent2 border-solid border-opacity-25 rounded-[5px]"]//parent::div/*[@stroke="currentColor"]',
    createGoalModal:'//div[text()="Create A Goal"]',
    goalTitle:'//span[text()="Goal Title"]//parent::div//textarea',
    goalYearDropDown:'//span[text()="Year"]//parent::div/*[@class="Input_inputContainer__AqMye"]',
    selectYearFromDropDown:'//div[text()="Calendar 2024"]',
    graphTypeDropDown:'//span[text()="Graph Type"]//parent::div/*[@class="Input_inputContainer__AqMye"]',
    selectGraphTypeLine:'//div[text()="Line Graph"]',
    selectGraphTypeBar:'//div[text()="Bar Graph"]',
    selectGraphTypeNone:'//div[text()="None"]',
    dataSourceDropDown:'//span[text()="Data Source"]//parent::div//div[@class=" css-5081g3-control"]',
    selectDataSourceCashRatio:'//div[text()="Cash Ratio"]',
    selectDataSourceQuickRatio:'//div[text()="Quick Ratio"]',
    selectDataSourceCurrentRatio:'//div[text()="Current Ratio"]',
    graphTargetValueField:'//span[text()="Graph Target Value"]//parent::div//div//input[@type="text"]',
    createGoalSaveBtn:'//button//div[text()="Save"]',
    confirmModal:'//span[text()="Please Confirm"]',
    yesBtn:'//div[text()="Yes"]//parent::button',
    yesOption:'//div[text()="Yes"]',
    clickCloseBtn:'//div[text()="Close"]',
    companyGoalMenuBtn:'//div[text()="Testing Goal 1558"]//parent::div//parent::div//parent::div//button[@class="szh-menu-button"]',
    unlockBtn:'//li[text()="Unlock"]',
    modalYesBtn:'//button//div[text()="Yes"]',
    lockBtn:'//li[text()="Lock"]',
    lockCompanyGoalModalHeading:'//span[text()="Lock Company Goal - Testing Goal 1558"]',
    companyGoalLockedSuccessMessage:'//div[text()="Company Goal locked!"]',
    companyGoalUnlockedSuccessMessage:'//div[text()="Company Goal Unlocked!"]',
    reorderBtn:'//button//div[text()="Reorder"]',
    reorderCompanyGoalModal:'//div[text()="Reorder Goals"]',
    searchCompanyGoalField:'input[placeholder="Search"]',
    dragGoal5907:'//li//span[text()="Testing Goal 5907"]',
    dropGoal8070:'//li//span[text()="Testing Goal 8070"]',
    saveBtn:'//div[text()="Save"]//parent::button',
    goalOrderChangeSuccessMessage:'//div[text()="Goals Order changed!"]',
    viewNotesBtn:'//li[text()="View Notes"]',
    internalNotesModalHeading:'//div[text()="Internal Notes"]',
    addNoteBtn:'//div[text()="Add Note"]',
    enternalNotesTextField:'//span[text()="Enter an Internal note"]//parent::div//parent::div//textarea',
    saveNoteBtn:'//button//div[text()="Save Note"]',
    noteAddedSuccessMessage:'//div[text()="Note Added!"]',
    notesMenuBtn:'//div[@class="flex items-center justify-between w-full gap-4"]//div//button',
    editNoteBtn:'//li[text()="Edit"]',
    editNotesTextField:'//div[@class="Input_mainContainer__z6cH9"]//div//textarea',
    noteUpdatedSuccessMessage:'//div[text()="Notes Updated!"]',
    removeNoteBtn:'//li[text()="remove"]',
    deleteInternalNotesModalHeading:'//span[text()="Delete Internal Note"]',
    noteRemovedSuccessMessage:'//div[text()="Note removed!"]',
    companyGoalMenuIcons:'.szh-menu-button',
    archiveBtn:'//li[text()="archive"]',
    goalArchivedSuccessMessage:'//div[text()="Goal Archived!"]',
    showArchiveIcon:'.text-neutrals5',
    restoreBtn:'//li[text()="restore"]',
    dataSetsMenuBtn:'//span[text()="Data Sets"]',
    createDataSetBtn:'//button//div[text()="Create Data Set"]',
    createDataSetPageHeading:'//span[text()="Create Data Set"]',
    enterDataSetNameField:'input[placeholder="Enter Data Set Name"]',
    monthAndYearDropDown:'//span[text()="Month & Year"]//parent::div//parent::div[@class="Input_inputContainer__AqMye"]',
    selectMonthAndYear:'//div[text()="August 2023"]',
    editMonthAndYear:'//div[text()="July 2023"]',
    createListBtn:'//button//div[text()="Create List"]',
    createListPageHeading:'//div[text()="Create A List"]',
    listName:'input[placeholder="e.g. Regions"]',
    listElement:'input[placeholder="e.g. North"]',
    addAnotherElementBtn:'//button//div[text()="Add Another Element"]',
    createBtn:'//button//div[text()="Create"]',
    listCreatedSuccessMessage:'//div[text()="List Created!"]',
    addVariableBtn:'//button//div[text()="Add Variable"]',
    addVariableModalHeading:'//div[text()="Create New Variable"]',
    variableNameTextField:'input[placeholder="Enter Variable Name"]',
    variableTypeDropDown:'//span[text()="Variable Type"]//parent::div//div[@class="Input_inputContainer__AqMye"]',
    selectVariableType:'//div[text()="Numeric"]',
    variablePropertyDropDown:'//div[@id="react-select-20-placeholder"]',
    selectVariableProperty:'//div[text()="Additive"]',
    variableDescriptionTextField:'textarea[placeholder="Enter Variable Description"]',
    saveAndGoBackBtn:'//button//div[text()="Save & Go Back"]',
    dataSetCreatedSuccessMessage:'//div[text()="Data Set Created!"]',
    editBtn:'//li[text()="Edit"]',
    saveChangesBtn:'//button//div[text()="Save Changes"]',
    dataSetUpdatedSuccessMessage:'//div[text()="Data Set Updated!"]',
    dataSetArchivedSuccessMessage:'//div[text()="Data Set archived!"]',
    restoreDataSetModalHeading:'//span[text()="Restore data set"]',
    restoreDataSetSuccessMessage:'//div[text()="Data Set restored!"]',
    listUpdatedSuccessMessage:'//div[text()="List Updated!"]',
    archiveListModalHeading:'//span[text()="Archive List"]',
    listArchivedSuccessMessage:'//div[text()="List archived!"]',
    restoreListModalHeading:'//span[text()="Restore List"]',
    restoreListSuccessMessage:'//div[text()="List restored!"]',
    profitRecommendationMenuBtn:'//span[text()="Profitability Recommendations"]',
    addProfitRecommendationBtn:'//div[text()="Add a Profit Recommendation"]',
    addRecommendationFormHeading:'//div[text()="Add a Profit Recommendation"]',
    recommendationTitleField:'//span[text()="Recommendation Title"]//parent::div//textarea',
    reportingPeriodDropDown:'//span[text()="Reporting Period"]//parent::div//div[@class="Input_inputContainer__AqMye"]',
    selectReportingPeriod:'//div[text()="November 2023"]',
    statusDropDown:'//span[text()="Status"]//parent::div//div[@class="Input_inputContainer__AqMye"]',
    selectInProgresStatus:'//div[text()="In Progress"]',
    selectImplementedStatus:'//div[text()="Implemented"]',
    outcomeField:'//span[text()="Outcome"]//parent::div//div[@class="Input_inputContainer__AqMye"]',
    selectNotImplementedStatus:'//div[text()="Not Implemented"]',
    profitrecommendationSuccessMessage:'//div[text()="Profit Recommendation created!"]',
    documentsMenuBtn:'//span[text()="Documents"]',
    createFolderBtn:'//div[text()="Create Folder"]',
    createFolderModalHeading:'//div[text()="Create Folder"]',
    folderNameField:'input[placeholder="Enter the folder name"]',
    folderCreatedSuccessMessage:'//div[text()="Folder created!"]',
    renameFolderModalHeading:'//div[text()="Rename Folder"]',
    renameOption:'//li[text()="Rename"]',
    renameBtn:'//div[text()="Rename"]',
    folderNameUpdatedSuccessMessage:'//div[text()="Folder name updated!"]',
    deleteOption:'//li[text()="Delete"]',
    deleteFolderModalHeading:'//span[text()="Delete Folder"]',
    folderDeletedSuccessMessage:'//div[text()="Folder deleted successfully"]',
    uploadBtn:'//div[text()="Upload"]',
    addDocumentsModalHeading:'//div[text()="Add Documents"]',
    uploadDocumentField:'input[type="file"]',
    documentUploadedSuccessMessage:'//div[text()="Document uploaded successfully"]',
    fileMeatBallMenuBtn:'//div[text()="test.txt"]//parent::div//parent::div//parent::div//button',
    editDocumentsModalHeading:'//div[text()="Edit Documents"]',
    displayNameField:'input[class="Input_input__rnmyh Input_lg__lcP1K"]',
    fileEditedSuccessMessage:'//div[text()="Document name updated!"]',
    deleteDocumentsModalHeading:'//span[text()="Delete Document"]',
    fileDeletedSuccessMessage:'//div[text()="Document Deleted Successfully"]',
    pdfFileMeatBallMenuBtn:'//div[text()="TGG-Document.pdf"]//parent::div//parent::div//parent::div//button',
    viewPdfOption:'//li[text()="View PDF"]',
}