const randomString = Math.floor(Math.random() * 100000).toString().padStart(5, '0')
import { faker } from '@faker-js/faker';
export const TestData={
    //Client spec test data
 instituationName: faker.internet.displayName(),
 contactFirstName: faker.person.firstName(),
 contactEmail: faker.internet.email({ firstName: 'Jeanne', lastName: 'Doe' }),
 executiveFirstName: faker.person.firstName(),
 executiveEmail: faker.internet.email({ firstName: 'Jeanne', lastName: 'Doe' }),
 clientUserFirstName: faker.person.firstName(),
 clientUserEmail: faker.internet.email({ firstName: 'Jeanne', lastName: 'Doe' }),
 longTermCompanyGoal: faker.lorem.sentence(),
 goalTitle: faker.internet.displayName(),
 graphTypeBarGoalTitle: faker.lorem.words(3),
 graphTypeNoneGoalTitle: faker.lorem.words(4),
 lockGoalTitle: faker.lorem.words(2),
 restoreGoalTitle: faker.internet.displayName(),
 archiveGoalTitle: faker.lorem.words(3),
 unlockGoalTitle: faker.internet.displayName(),
 goalTitle: faker.internet.displayName(),
 goalNotes: faker.lorem.sentence(),
 dataSetName: faker.lorem.words(2),
 editDataSetName: faker.lorem.words(3),
 archiveDataSetName: faker.lorem.words(4),
 restoreDataSetName: faker.lorem.words(1),
 listName: faker.internet.displayName(),
 restoreListName: faker.lorem.words(3),
 archiveListName: faker.lorem.words(4),
 editListName: faker.lorem.words(2),
 listElement: faker.lorem.word(),
 restoreListElement: faker.lorem.words(2),
 archiveListElement: faker.lorem.words(3),
 editListElement: faker.lorem.words(4),
 variableName: faker.lorem.words(2),
 description: faker.lorem.sentences(1),
 folderName: faker.lorem.words(2),
 renameFolderName: faker.lorem.words(3),
 deleteFolderName: faker.lorem.words(4),
 uploadDocFolderName: faker.lorem.words(3),
 renameDocName: faker.lorem.words(1),
 deleteDocName: faker.lorem.words(2),
 viewDocName: faker.lorem.words(3),
 renameFolder: `Renamed Folder ${randomString}`,

 //Agency spec test data
 agencyName: faker.internet.displayName(),
 deactiveAgencyName: faker.lorem.words(2),
 agencyAddress: faker.location.streetAddress(),
 agencyCity: faker.location.city(),
 agencySlug: faker.lorem.slug(),
 clientName: faker.person.fullName(),
 orgAddress1: faker.location.streetAddress(),
 orgCity: faker.location.city(),
 orgWebsite: `test${randomString}.com`,
 orgTagline: faker.lorem.sentences(1),
 orgBusinessOverview: faker.lorem.sentences(4),
 hubAnalyticUserFirstName: faker.person.firstName(),
 hubAnalyticUserLastName: faker.person.lastName(),
}
